# This is a basic workflow to help you get started with Actions

name: Linux-Flatpak CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Setup Packages
    - name: Setup Packages
      run: sudo apt update && sudo apt upgrade && sudo apt install build-essential git cmake ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libevdev-dev libusb-1.0-0-dev libxrandr-dev libxi-dev libpangocairo-1.0-0 qt6-base-private-dev libbluetooth-dev libasound2-dev libpulse-dev libgl1-mesa-dev libudev-dev libsystemd-dev dpkg-dev flatpak flatpak-builder
    # Setup Flatpak
    - name: Setup Flatpak SDK
      run: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && flatpak install org.kde.Sdk//5.15 org.kde.Platform//5.15 -y
    # Run Flatpak Builder
    - name: Run Flatpak Builder
      run: flatpak-builder --repo=/home/runner/work/Dolphin-MPN-src/Dolphin-MPN-src/.flatpak/repo /home/runner/work/Dolphin-MPN-src/Dolphin-MPN-src/build /home/runner/work/Dolphin-MPN-src/Dolphin-MPN-src/.flatpak/flatpak.yml
    # Flatpak Build Bundle 
    - name: Run Flatpak Bundler
      run: flatpak build-bundle /home/runner/work/Dolphin-MPN-src/Dolphin-MPN-src/.flatpak/repo DolphinMPN.flatpak org.DolphinEmu.dolphin-mpn\
    # Upload Artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DolphinMPN-Linux
        path: /home/runner/work/Dolphin-MPN-src/Dolphin-MPN-src/.flatpak
