# This is a basic workflow to help you get started with Actions

name: Windows CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Submoudle
    - name: Checkout Submodles
      run: git submodule update --init --recursive
    # Install 7zip
    - name: Install 7zip
      run: choco install 7zip
    # Setup MSBuild For Later Usage
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '16.6.2'
    # Run MSBuild
    - name: Build Solution
      run: msbuild "D:\a\Dolphin-MPN-src\Dolphin-MPN-src\Source\dolphin-emu.sln" /verbosity:minimal /property:Configuration=Release  /property:Platform=x64
    # Upload Artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DolphinMPN-win32
        path: D:\a\Dolphin-MPN-src\Dolphin-MPN-src\Binary\x64
    # Zip Artifact
    - name: Zip Artifact
      run: 7z a D:/DolphinMPN-win32 D:/a/dolphin-mpn-src/dolphin-mpn-src/Binary/x64/*
